### ISSUE TITLE
Max height

### ISSUE THREAD

**Issue by 00c** [AndrejIT/map_unexplore#2]
There is option to set max depth in remap.py Is it possible to add max height
` if pos[0]**2 + pos[2]**2 < (160/16)**2 and pos[1]>(-60/16): #160 nodes radius and 60 nodes deep`

**Comment by AndrejIT** [comment]
You can change like this, but it will not make big difference, because usually above is just air.
`if pos[0]**2 + pos[2]**2 < (160/16)**2 and pos[1]>(-60/16) and pos[1]<(60/16): #160 nodes radius and 60 nodes deep and 60 nodes high`
